config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get '/' => 'home#top'

  resources :events do
    member do
      post 'join'
      post 'leave'
    end
    collection do
      get 'search'
    end
  end
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  resources :users, :only => [:index]

  # blockの最後に以下を追加
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_images
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users
  accepts_nested_attributes_for :event_users
  geocoded_by :address
  after_validation :geocode

  mount_uploader :image, ImageUploader

  def self.get_sponsorship_events user_id
    EventUser.where('user_id = ? AND admin = ?', user_id, true)
  end

  def self.search_sponsorship_events user_id, event_id
    EventUser.where('user_id = ? AND event_id = ? AND admin = ?', user_id, event_id, true)
  end

  def self.get_invited_events user_id
    EventUser.where('user_id = ? AND admin = ?', user_id, false)
  end

  def self.search_participateds_events user_id, event_id
    EventUser.where('user_id = ? AND event_id = ? AND admin = ?', user_id, event_id, false)
  end

  validates :name, {presence: true, length: {maximum: 255}}
  validates :description, length: {maximum: 65535}
  validates :location_name, length: {maximum: 255}
  validates :location_url, length: {maximum: 65535}
  validates :location_url, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
  validates :address, length: {maximum: 65535}
  validates :link, length: {maximum: 65535}
  validates :link, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    if event_date.present? && event_date < Date.today
      errors.add('開催日', ': 過去の日付は使用できません')
    end
  end
end

app/models/search/event.rb
class Search::Event < Search::Base
  ATTRIBUTES = %i(
    name
    event_date
    address
    description
  )
  attr_accessor(*ATTRIBUTES)

  def matches
    t = ::Event.arel_table
    results = ::Event.all
    p 'name'
    p name
    results = results.where(contains(t[:name], name)) if name.present?
    results = results.where('DATE(event_date) = ?', event_date) if event_date.present?
    results = results.where(contains(t[:address], address)) if address.present?
    results = results.where(contains(t[:description], description)) if description.present?
    results
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @sponsorship_events = Event.get_sponsorship_events(current_user.id)
    invited_events = Event.get_invited_events(current_user.id)
    @participateds_events = invited_events.select { |event| EventsHelper.is_join?(event.status) }
    @invited_events = invited_events.select { |event| EventsHelper.is_leave?(event.status) }
    @event = Search::Event.new
  end

  def search
    @event = Search::Event.new(search_params)
    @events = @event.matches
    @sponsorship_events = []
    invited_events = []

    @events.each do |e|
      sponsorship_events = Event.search_sponsorship_events(current_user.id, e.id)
      sponsorship_events.each do |sponsorship_event|
        @sponsorship_events.push(sponsorship_event)
      end
      participateds_events = Event.search_participateds_events(current_user.id, e.id)
      participateds_events.each do |participateds_event|
        invited_events.push(participateds_event)
      end
    end
    @participateds_events = invited_events.select { |event| EventsHelper.is_join?(event.status) }
    @invited_events = invited_events.select { |event| EventsHelper.is_leave?(event.status) }
  end

  def join
    @event = Event.find_by(id: params[:id])
    event_user = EventUser.get_one(current_user.id, @event.id)
    event_user.status = 1
    if event_user.save
      redirect_to(events_path)
    end
  end

  def leave
    @event = Event.find_by(id: params[:id])
    event_user = EventUser.get_one(current_user.id, @event.id)
    event_user.status = 0
    if event_user.save
      redirect_to(events_path)
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find_by(id: params[:id])
    if @event.latitude.present? && @event.longitude.present?
      @lat_lng = {lat: @event.latitude, lng: @event.longitude}
    else
      @lat_lng = {lat: '', lng: ''}
    end
    @address = @event.address
    @admin = EventUser.is_admin?(current_user.id, @event.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    unless EventUser.is_admin?(current_user.id, params[:id])
      redirect_to(events_path)
    end
  end

  # POST /events
  # POST /events.json
  def create
    # イベント作成者は管理者となる
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        # TODO もっと良い方法が確実にある
        events_user = EventUser.new(user_id: current_user.id, event_id: @event.id, admin: true)
        events_user.save
        format.html { redirect_to @event, notice: 'イベントを作成しました。' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    unless  EventUser.is_admin?(current_user.id, params[:id])
      redirect_to(events_path)
    end

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'イベントを更新しました。' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    unless EventUser.is_admin?(current_user.id, params[:id])
      redirect_to(events_path)
    end

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'イベントを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {}).permit(:image, :name, :event_date, :address, :location_name, :location_url, :capacity, :description, :link)
    end

    def search_params
      params
          .require(:search_event)
          .permit(Search::Event::ATTRIBUTES)
    end

    def authenticate
      redirect_to '/' unless user_signed_in?
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def self.is_join? status
    return status == 1
  end

  def self.is_leave? status
    return status == 0
  end
end

app/views/events/_footer.html.erb
<footer>
  <div class="container">
    <a href="#" class="scrollpoint sp-effect3 active animated fadeInDown">
      <img src="/images/together-logo-white.png" alt="">
    </a>
    <div class="social">
      <a href="https://twitter.com/ITTAN_inc" class="scrollpoint sp-effect3 active animated fadeInDown" target="_blank">
        <%= fa_icon 'twitter' %>
      </a>
      <!--<a href="#" class="scrollpoint sp-effect3 active animated fadeInDown">-->
        <!--<%= fa_icon 'instagram' %>-->
      <!--</a>-->
      <a href="https://www.facebook.com/ITTAN-126350964755208/" class="scrollpoint sp-effect3 active animated fadeInDown" target="_blank">
        <%= fa_icon 'facebook' %>
      </a>
    </div>
    <div class="rights">
      <p>Copyright © 2017</p>
      <p><a href="http://www.ittan.website" target="_blank">ITTAN</a></p>
    </div>
    <!--<div class="links row">-->
      <!--&lt;!&ndash;TODO リンク先決めねば&ndash;&gt;-->
      <!--<div class="col-xs-12 col-md-3 text-center">-->
        <!--<a>お問い合わせ</a>-->
      <!--</div>-->
      <!--<div class="col-xs-12 col-md-3 text-center">-->
        <!--<a>運営会社</a>-->
      <!--</div>-->
      <!--<div class="col-xs-12 col-md-3 text-center">-->
        <!--<a>利用規約</a>-->
      <!--</div>-->
      <!--<div class="col-xs-12 col-md-3 text-center">-->
        <!--<a>プライバシーポリシー</a>-->
      <!--</div>-->
    <!--</div>-->
  </div>
</footer>

app/views/events/index.html.erb
<div class="container">
  <div id="event-index">
    <% if notice %>
      <div class="alert alert-success"><p id="notice"><%= notice %></p></div>
    <% end %>

    <h1>イベントを検索する</h1>

    <%= form_for(@event, url: search_events_path, html: { method: :get, role: 'form' }) do |f| %>
        <div class="row justify-content-md-center">
          <div class="col-md-6">
            <%= f.text_field :name, class: 'form-control-g', placeholder: 'タイトル', maxlength: '255' %>
          </div>
          <div class="col-md-6">
            <%= f.date_field :event_date, id: 'event-date', class: 'form-control-g', placeholder: '開催日', value: (@event.event_date || Time.now.strftime("%Y-%m-%d")) %>
          </div>
        </div>
        <div class="row justify-content-md-center">
          <div class="col-md-6">
            <%= f.text_field :address, class: 'form-control-g', placeholder: '開催場所', maxlength: '65535' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :description, class: 'form-control-g', placeholder: '内容', maxlength: '65535' %>
          </div>
        </div>
        <div class="row justify-content-md-center">
          <div class="col-md-12 text-right">
            <%= f.submit '検索', class: 'button-blue-g px-5' %>
          </div>
        </div>
    <% end %>

    <div class="row justify-content-md-center">
      <div class="col-md-12 text-right">
        <%= link_to 'イベントを作成する', new_event_path, class: 'button-green-g px-5' %>
      </div>
    </div>

    <div>
      <h2>主催のイベント</h2>
      <div class="row">
        <% @sponsorship_events.each do |sponsorship_event| %>
            <div class="col-sm-12 col-md-4">
              <%= link_to(sponsorship_event.event) do %>
                <div class="event">
                  <div class="image text-center">
                    <% if sponsorship_event.event.image.present? then %>
                        <%= image_tag sponsorship_event.event.image %>
                    <% else %>
                        <%= image_tag '/images/no-image.png' %>
                    <% end %>
                  </div>
                  <div class="info">
                    <div class="date">
                      <% if sponsorship_event.event.event_date.present? then %>
                          <%= sponsorship_event.event.event_date.strftime('%Y/%m/%d') %>
                      <% end %>
                    </div>
                    <div class="name">
                      <%= sponsorship_event.event.name %>
                    </div>
                    <div class="capacity">
                      <%= custom_format(sponsorship_event.event.capacity, '人') %>
                    </div>
                    <div class="event-button text-right">
                      <% if is_admin?(current_user.id, sponsorship_event.event.id) then %>
                        <%= link_to 'イベントを編集', edit_event_path(sponsorship_event.event), class: 'button-green-g px-2' %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
        <% if @sponsorship_events.empty? %>
          <div class="no-hosted-event">
            <p>主催のイベントはありません</p>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <h2>参加予定のイベント</h2>
      <div class="row">
        <% @participateds_events.each do |participateds_event| %>
          <div class="col-sm-12 col-md-4">
            <%= link_to (participateds_event.event) do %>
              <div class="event">
                <div class="image text-center">
                  <% if participateds_event.event.image.present? then %>
                      <%= image_tag participateds_event.event.image %>
                  <% else %>
                      <%= image_tag '/images/no-image.png' %>
                  <% end %>
                </div>
                <div class="info">
                  <div class="date">
                    <% if participateds_event.event.event_date.present? then %>
                        <%= participateds_event.event.event_date.strftime('%Y/%m/%d') %>
                    <% end %>
                  </div>
                  <div class="name">
                    <%= participateds_event.event.name %>
                  </div>
                  <div class="capacity">
                    <%= custom_format(participateds_event.event.capacity, '人') %>
                  </div>
                  <div class="event-button text-right">
                    <% if is_admin?(current_user.id, participateds_event.event.id) then %>
                        <%= link_to 'イベントを編集', edit_event_path(participateds_event.event), class: 'button-green-g px-2' %>
                    <% end %>
                  </div>
                  <% if is_join?(participateds_event.status) then %>
                      <div><%= link_to '参加を見送る', leave_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                  <% if is_leave?(participateds_event.status) then %>
                      <div><%= link_to '参加する', join_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if @participateds_events.empty? %>
            <div class="no-hosted-event">
              <p>参加予定のイベントはありません</p>
            </div>
        <% end %>
      </div>
    </div>

    <div>
      <h2>招待されているイベント</h2>
      <div class="row">
        <% @invited_events.each do |participateds_event| %>
          <div class="col-sm-12 col-md-4">
            <%= link_to (participateds_event.event) do %>
              <div class="event">
                <div class="image text-center">
                  <% if participateds_event.event.image.present? then %>
                      <%= image_tag participateds_event.event.image %>
                  <% else %>
                      <%= image_tag '/images/no-image.png' %>
                  <% end %>
                </div>
                <div class="info">
                  <div class="date">
                    <% if participateds_event.event.event_date.present? then %>
                        <%= participateds_event.event.event_date.strftime('%Y/%m/%d') %>
                    <% end %>
                  </div>
                  <div class="name">
                    <%= participateds_event.event.name %>
                  </div>
                  <div class="capacity">
                    <%= custom_format(participateds_event.event.capacity, '人') %>
                  </div>
                  <div>
                    <% if is_admin?(current_user.id, participateds_event.event.id) then %>
                        <%= link_to 'イベントを編集', edit_event_path(participateds_event.event), class: 'button-green-g px-2' %>
                    <% end %>
                  </div>
                  <% if is_join?(participateds_event.status) then %>
                      <div><%= link_to '参加を見送る', leave_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                  <% if is_leave?(participateds_event.status) then %>
                      <div><%= link_to '参加する', join_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if @invited_events.empty? %>
            <div class="no-hosted-event">
              <p>招待されているイベントはありません</p>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>
<%= render 'footer' %>

app/views/events/new.html.erb
<div class="container">
  <div id="event-new">
    <h1>イベント作成</h1>

    <%= render 'form', event: @event %>
    <div class="row justify-content-center mb-2">
      <%= link_to 'マイページに戻る', events_path, class: 'button-green-g px-3 m-1' %>
    </div>
  </div>
</div>
<%= render 'footer' %>

app/views/events/search.html.erb
<div class="container">
  <div id="event-index">
    <% if notice %>
        <div class="alert alert-success"><p id="notice"><%= notice %></p></div>
    <% end %>

    <h1>イベントを検索する</h1>

    <%= form_for(@event, url: search_events_path, html: { method: :get, role: 'form' }) do |f| %>
        <div class="row justify-content-md-center">
          <div class="col-md-6">
            <%= f.text_field :name, class: 'form-control-g', placeholder: 'タイトル', maxlength: '255' %>
          </div>
          <div class="col-md-6">
            <%= f.date_field :event_date, id: 'event-date', class: 'form-control-g', placeholder: '開催日', value: (@event.event_date || Time.now.strftime("%Y-%m-%d")) %>
          </div>
        </div>
        <div class="row justify-content-md-center">
          <div class="col-md-6">
            <%= f.text_field :address, class: 'form-control-g', placeholder: '開催場所', maxlength: '65535' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :description, class: 'form-control-g', placeholder: '内容', maxlength: '65535' %>
          </div>
        </div>
        <div class="row justify-content-md-center">
          <div class="col-md-12 text-right">
            <%= f.submit '検索', class: 'button-blue-g px-5' %>
          </div>
        </div>
    <% end %>

    <div class="row justify-content-md-center">
      <div class="col-md-12 text-right">
        <%= link_to 'イベントを作成する', new_event_path, class: 'button-green-g px-5' %>
      </div>
    </div>

    <div>
      <h2 class="h3">主催のイベント</h2>
      <div class="row">
        <% @sponsorship_events.each do |sponsorship_event| %>
            <div class="col-sm-4">
              <div class="event">
                <div class="image text-center">
                  <% if sponsorship_event.event.image.present? then %>
                      <%= image_tag sponsorship_event.event.image %>
                  <% else %>
                      <%= image_tag '/images/no-image.png' %>
                  <% end %>
                </div>
                <div class="info">
                  <div class="date">
                    <% if sponsorship_event.event.event_date.present? then %>
                        <%= sponsorship_event.event.event_date.strftime('%Y/%m/%d') %>
                    <% end %>
                  </div>
                  <div class="name">
                    <%= sponsorship_event.event.name %>
                  </div>
                  <div class="capacity">
                    <%= custom_format(sponsorship_event.event.capacity, '人') %>
                  </div>
                  <div>
                    <!-- <%= link_to 'イベントの詳細', sponsorship_event.event, class: 'button-green-g px-2' %> -->

                    <% if is_admin?(current_user.id, sponsorship_event.event.id) then %>
                      <div class="event-button text-right">
                        <%= link_to 'イベントを編集', edit_event_path(sponsorship_event.event), class: 'button-green-g px-2' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
        <% if @sponsorship_events.empty? %>
            <div class="no-hosted-event">
              <p>主催のイベントはありません</p>
            </div>
        <% end %>
      </div>
    </div>

    <div>
      <h2>参加予定のイベント</h2>
      <div class="row">
        <% @participateds_events.each do |participateds_event| %>
            <div class="col-sm-4">
              <div class="event">
                <div class="image text-center">
                  <% if participateds_event.event.image.present? then %>
                      <%= image_tag participateds_event.event.image %>
                  <% else %>
                      <%= image_tag '/images/no-image.png' %>
                  <% end %>
                </div>
                <div class="info">
                  <div class="date">
                    <% if participateds_event.event.event_date.present? then %>
                        <%= participateds_event.event.event_date.strftime('%Y/%m/%d') %>
                    <% end %>
                  </div>
                  <div class="name">
                    <%= participateds_event.event.name %>
                  </div>
                  <div class="capacity">
                    <%= custom_format(participateds_event.event.capacity, '人') %>
                  </div>
                  <div class="event-button text-right">
                    <% if is_admin?(current_user.id, participateds_event.event.id) then %>
                        <%= link_to 'イベントを編集', edit_event_path(participateds_event.event), class: 'button-green-g px-2' %>
                    <% end %>
                  </div>
                  <% if is_join?(participateds_event.status) then %>
                      <div><%= link_to '参加を見送る', leave_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                  <% if is_leave?(participateds_event.status) then %>
                      <div><%= link_to '参加する', join_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
        <% if @participateds_events.empty? %>
            <div class="no-hosted-event">
              <p>参加予定のイベントはありません</p>
            </div>
        <% end %>
      </div>
    </div>

    <div>
      <h2>招待されているイベント</h2>
      <div class="row">
        <% @invited_events.each do |participateds_event| %>
            <div class="col-sm-4">
              <div class="event">
                <div class="image text-center">
                  <% if participateds_event.event.image.present? then %>
                      <%= image_tag participateds_event.event.image %>
                  <% else %>
                      <%= image_tag '/images/no-image.png' %>
                  <% end %>
                </div>
                <div class="info">
                  <div class="date">
                    <% if participateds_event.event.event_date.present? then %>
                        <%= participateds_event.event.event_date.strftime('%Y/%m/%d') %>
                    <% end %>
                  </div>
                  <div class="name">
                    <%= participateds_event.event.name %>
                  </div>
                  <div class="capacity">
                    <%= custom_format(participateds_event.event.capacity, '人') %>
                  </div>
                  <div>
                    <% if is_admin?(current_user.id, participateds_event.event.id) then %>
                        <%= link_to 'イベントを編集', edit_event_path(participateds_event.event), class: 'button-green-g px-2' %>
                    <% end %>
                  </div>
                  <% if is_join?(participateds_event.status) then %>
                      <div><%= link_to '参加を見送る', leave_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                  <% if is_leave?(participateds_event.status) then %>
                      <div><%= link_to '参加する', join_event_path(participateds_event.event.id), method: :post %></div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
        <% if @invited_events.empty? %>
            <div class="no-hosted-event">
              <p>招待されているイベントはありません</p>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>
<%= render 'footer' %>

app/views/events/show.html.erb
<script>
  $(function(){
    var domain = <%= current_env %>;
    switch (domain) {
      case 'development':
        domain = 'localhost:3000'
        break;
      case 'test':
        // TODO
        break;
      case 'production':
        domain = 'www.ittan-together.com'
        break;
    }
    $('#invitation-url').val('http://' + domain + '/users/sign_up?event_id='+<%= raw @event.id %>)
    $('#publish-url').on('click', function () {
      $('#invitation').css('display', 'block');
      $('#url-copy').on('click', function () {
        $('#invitation-url')[0].focus();
        $('#invitation-url')[0].select();
        document.execCommand('copy');
        $('#invitation').css('display', 'none');
      });
      $('#invitation-close').on('click', function () {
        $('#invitation').css('display', 'none');
      });
    });
  });
</script>

<script type="text/javascript">
    function initMap() {

      if (<%= raw @address.to_json %>){
        var test = <%= raw @lat_lng.to_json %>;
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @address %>';
        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        var marker = new google.maps.Marker({
          position:test,
          map: map,
          title: contentString
        });

        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      }
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyD_KJLZR-bo1pDgbrT0VCZ60zN93joI57U&callback=initMap">
</script>

<div class="container">
  <div id="event-show">
    <% if notice %>
        <div class="alert alert-success"><p id="notice"><%= notice %></p></div>
    <% end %>
    <div class="row">
      <h1 class="col-md-5 col-sm-12"><%= @event.name %></h1>
      <div class="col-md-7 col-sm-12 text-right mt-3">
        <% if @admin %>
          <button id="publish-url" class="button-green-g">招待URL発行</button>
        <% end %>
      </div>
    </div>
    <div id="invitation">
      <div class="header">招待URL</div>
      <div class="body">
        <input id="invitation-url" value="" size="30" class="form-control mb-3">
        <div class="text-right">
          <button id="url-copy" class="btn btn-primary">コピー</button>
          <button id="invitation-close" class="btn btn-default">閉じる</button>
        </div>
      </div>
    </div>
    <h2>基本情報</h2>
    <div class="row">
      <div class="col-sm-12">
        <% if @event.image.present? then %>
            <%= image_tag @event.image.thumb, class: '' %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7 col-sm-12">
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-calendar fa-1x" aria-hidden="true"></i>開催日</label>
          <% if @event.event_date.present? then %>
              <div class="col-md-8 col-sm-12"><%= l(@event.event_date, format: :long) %></div>
          <% end %>
        </div>
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-home fa-1x" aria-hidden="true"></i>会場</label>
          <div class="col-md-8 col-sm-12">
            <%= @event.location_name %>
            <% if @event.location_url.present? then %>
              <%= link_to '', @event.location_url, class: 'icon fa fa-link ml-2' %>
            <% end %>
          </div>
        </div>
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-map-marker fa-1x" aria-hidden="true"></i>住所</label>
          <div class="col-md-8 col-sm-12"><%= @event.address %></div>
        </div>
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-user fa-1x" aria-hidden="true"></i>定員</label>
          <div class="col-md-8 col-sm-12"><%= @event.capacity %></div>
        </div>
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-file-text-o fa-1x" aria-hidden="true"></i>説明</label>
          <div class="col-md-8 col-sm-12"><%= simple_format(@event.description) %></div>
        </div>
        <div class="row border-bottom">
          <label class="col-md-4 col-sm-12"><i class="fa fa-link fa-1x" aria-hidden="true"></i>関連リンク</label>
          <div class="col-md-8 col-sm-12"><%= @event.link %></div>
        </div>
        <div class="row">
          <label class="col-md-4 col-sm-12"><i class="fa fa-users fa-1x" aria-hidden="true"></i><%= "参加者（#{getParticipant(@event.event_users)}人）" %></label>
        </div>
        <div class="row">
          <% @event.event_users.each do |event_user| %>
              <% if event_user.user.image.present? && (event_user.status == 1 || event_user.admin) then %>
                  <div class="user-cube col-sm-2 col-4">
                    <%= image_tag event_user.user.image.thumb %>
                    <div class="user-name">
                      <%= event_user.user.name %>
                    </div>
                  </div>
              <% elsif event_user.status == 1 || event_user.admin %>
                  <div class="user-cube col-sm-2 col-4">
                    <%= image_tag '/images/no-image.png' %>
                    <div class="user-name">
                      <%= event_user.user.name %>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
        <div class="row">
          <label class="col-md-4 col-sm-12"><i class="fa fa-user-o fa-1x" aria-hidden="true"></i>管理者</label>
        </div>
        <div class="row">
          <% @event.event_users.each do |event_user| %>
              <% if event_user.admin && event_user.user.image.present? then %>
                  <div class="user-cube col-sm-2 col-4">
                    <%= image_tag event_user.user.image.thumb %>
                    <div class="user-name">
                      <%= event_user.user.name %>
                    </div>
                  </div>
              <% elsif event_user.admin %>
                  <div class="user-cube col-sm-2 col-4">
                    <%= image_tag '/images/no-image.png' %>
                    <div class="user-name">
                      <%= event_user.user.name %>
                    </div>
                  </div>
              <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-5 col-sm-12">
        <div class="row"><div id="map"></div></div>
      </div>
    </div>

    <div class="button-group">
      <% if is_admin?(current_user.id, @event.id) then %>
          <div class="row justify-content-md-center mb-2">
            <%= link_to 'イベントを編集', edit_event_path(@event), class: 'button-green-g px-5 text-center' %>
          </div>
          <div class="row justify-content-md-center mb-2">
            <%= link_to 'イベントを削除', @event, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'button-red-g px-5 text-center' %>
          </div>
      <% end %>
      <div class="row justify-content-md-center mb-2">
        <%= link_to '戻る', events_path, class: 'button-green-g px-3 text-center' %>
      </div>
    </div>

  </div>

</div>
<%= render 'footer' %>